// The Apps Script's "Last updated" stamp is real.
//
// That header line exists for one job: telling somebody about to paste the
// script into the Apps Script editor whether what they are holding is newer
// than what is already in Google.
//
// It failed at that job. Typed by hand, it sat at 26 August through several
// changes and was eventually read as proof the file had not been updated when
// it had, which cost a round trip to find out otherwise.
//
// So the stamp is now generated by scripts/stamp-gs.py and checked here. The
// header carries a fingerprint of the file body, and this recomputes it: edit
// the script without stamping it and the fingerprint no longer matches, so
// the date cannot silently go stale again.
//
//   node tests/stamp.test.cjs
//
const crypto = require("crypto");
const fs = require("fs");
const path = require("path");

const REL = "google-apps-script/mailing-list.gs";
const SRC = fs.readFileSync(path.join(__dirname, "..", REL), "utf8");

// Must match BODY_MARKER in scripts/stamp-gs.py.
const BODY_MARKER = "const SPREADSHEET_ID";

let pass = 0, fail = 0;
const check = (n, c, x) => c ? (pass++, console.log("  PASS " + n))
                             : (fail++, console.log("  FAIL " + n + (x ? " -> " + x : "")));

console.log("\n=== the header stamp matches the file ===");

const bodyAt = SRC.indexOf(BODY_MARKER);
check("the body marker is still where the stamper expects it", bodyAt !== -1,
  "could not find " + BODY_MARKER);

const stampLine = (SRC.match(/^\/\/ Last updated: (.*)$/m) || [])[1];
const fpLine = (SRC.match(/^\/\/ Fingerprint:  (.*)$/m) || [])[1];

check("there is a Last updated line", !!stampLine, String(stampLine));
check("  in a sortable, unambiguous format",
  /^\d{4}-\d{2}-\d{2} \d{2}:\d{2} UTC$/.test(stampLine || ""), String(stampLine));
check("there is a Fingerprint line", !!fpLine, String(fpLine));
check("  which is eight hex characters", /^[0-9a-f]{8}$/.test(fpLine || ""), String(fpLine));

if (bodyAt !== -1) {
  const actual = crypto.createHash("sha256")
    .update(SRC.slice(bodyAt), "utf8").digest("hex").slice(0, 8);

  check("the fingerprint matches the code below it", fpLine === actual,
    "header says " + fpLine + ", file is " + actual +
    "\n         The script has been edited without re-stamping." +
    "\n         Run: python3 scripts/stamp-gs.py");
}

// A stamp in the future is either a wrong clock or a typo, and either way it
// makes the comparison against Google's copy meaningless.
if (stampLine) {
  const when = new Date(stampLine.replace(" UTC", "Z").replace(" ", "T"));
  check("the stamp parses as a real time", !isNaN(when), stampLine);
  check("  and is not in the future", !isNaN(when) && when.getTime() <= Date.now() + 60000,
    stampLine + " vs now " + new Date().toISOString());
}

// The header prose is deliberately outside the fingerprint, so that improving
// an explanation does not masquerade as a new version of the script. Guard
// that boundary: if the marker ever moved above the header, every comment
// edit would start demanding a re-stamp.
console.log("\n=== the fingerprint covers code, not commentary ===");
{
  const header = SRC.slice(0, bodyAt);
  check("the header is prose only, no code",
    header.split("\n").every((l) => l.trim() === "" || l.trim().startsWith("//")),
    header.split("\n").filter((l) => l.trim() && !l.trim().startsWith("//"))[0]);
  check("  and it explains how to re-stamp",
    /scripts\/stamp-gs\.py/.test(header));
}

console.log("\n" + pass + " passed, " + fail + " failed");
process.exit(fail ? 1 : 0);
